### PR TITLE
Timeline Page

### PR DESCRIPTION
**Pull request by DonXavierdev**
Fixes https://github.com/ohcnetwork/landing/issues/37

### CODE REVIEW

**Comment by DonXavierdev** [comment]
@bodhish  - Can you please check the deploy preview and review the timeline page? I created the page based on the care product page. Can you add comments on this design?

**Review by shivankacker — CHANGES_REQUESTED** [review]
@DonXavierdev 
I like the design, but a few suggestions:

- Can we move the year above the title and give it another kind of highlight?
- Can we have a line that is going from top to bottom, with the years being pitstops?

**Comment by DonXavierdev** [comment]
@shivankacker i have made the requested changes, but the vertical line didn't look consistent with other designs so i added the same logic with year being pitstops as a navigation section for the contents. Let me know if this is ok or if changes are to be made

**Comment by rithviknishad** [comment]
@DonXavierdev you can re-request for review by clicking this btw:

makes it easier for us to track what's pending to be reviewed.


image

**Review by shivankacker — CHANGES_REQUESTED** [review]
@DonXavierdev 

The previous alignment of content was better, left alignment is not looking so great ☹️

There needs to be support for small laptop sizes. Here is how I see it in Arc browser:

image

Have a look at this design, for lines and pitstops:
image

I am fine with there not being a sidebar here, does not add much value and is taking up space 🤔

**Comment by DonXavierdev** [comment]
@shivankacker 

the design was:

Screenshot 2024-12-20 at 11 00 22 AM

I think i only put it for screen sizes of XL instead of putting it for lg and larger. Sorry for that. The design you came across was meant for smaller screen sizes. 

also the sidebar was clickable and would instantly get you to that section of the timeline.  

i am already working on implementing a similar design to what you shared. Thanks for that. Just putting this out there to actually show you how it was.

**Comment by DonXavierdev** [comment]
proceeding with this :

Screenshot 2024-12-20 at 12 16 03 PM

**Comment by shivankacker** [comment]
@DonXavierdev looks good 🔥

**Comment by DonXavierdev** [comment]
@shivankacker please check the changes. pushed changes with pitstop added.

**Review by shivankacker — APPROVED** [review]

**Pull request merged**
