### PR TITLE
[bug-fix] Now community link dropdown does not flys-off

### LINKED ISSUE #10: Community Fly-out Menu seems to hide itself unless you move your cursor through the desired path.

### PR DESCRIPTION
**Pull request by thecodephilic-guy**
Fixes #10 
Removed the onHover behaviour and added onClick.
Now users don't need to come through a desired path to make the dropdown open.
Fixed the header view for mobile now text is a bit smaller.

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

**Review by shivankacker — CHANGES_REQUESTED** [review]
@thecodephilic-guy I don't think switching to click from hover is good from a user experience POV. Can we stick to hover?

**Comment by thecodephilic-guy** [comment]
I tried sticking to the style of its neighbouring buttons. All of them were clickable except "Community" that felt a bit off.

**Comment by shivankacker** [comment]
@thecodephilic-guy we usually toggle sub menus on hover and click for direct links. This is followed in most websites. Do you think you can solve the issue while retaining the hover logic?

**Comment by thecodephilic-guy** [comment]
Of course I can solve it, and I'll do that.

**Comment by thecodephilic-guy** [comment]
All set, just added another ref to the header container and appended that ref in the onMouseMove funtion to tell that do not close it when user hover in the left side of the button.

**Comment by shivankacker** [comment]
@thecodephilic-guy yep this does fix it, but now there is a small issue. When you hover over the link and move your mouse to the left, the dropdown does not disappear (Attached recording). Maybe another ref can fix that?

https://github.com/user-attachments/assets/86894ecd-27b9-4634-9ad3-a0b8bf258144

**Comment by thecodephilic-guy** [comment]
That was the only issue right? 😅

I mean in the issue it was mentioned that user has to come through a desired cursor path so that drop-down doesn't close. I myself felt this weird. So now that's not the case the user can now come from the left side of the community button and and still the drop-down will not close.

**Comment by shivankacker** [comment]
@thecodephilic-guy The issue was that the user should not have to move in a straight line to make sure the panel does not close. However moving away from the panel/button for a long time should technically close it. But it does make the issue kind of complex to deal with, which is why it was abstracted out to a separate issue from a parent issue.
I think it is probably best not to delve into such complexity at this time for a small change, so the current solution you have presented works great. Looks good to me. Thank you for contributing!

**Review by shivankacker — APPROVED** [review]

**Pull request merged**
